config:
  cat_motor_device_config: &cat_motor_device_config
    <<: *Usr_Motor_Init_Config
    <<: *Motor_default_config

  Motor_Config_Normal_0: &Motor_Config_Normal_0
    DeviceType: Motor_Device 
    CH: Head_Flag_Switch_CH2
    IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

  MotorS_0: &MotorS_0
    - Name: Motor_6
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config
        
    - Name: Motor_5
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_4
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_3
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_2
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config
        DI_I_MAX: 0.4
        Gear_multiple: 4

    - Name: Motor_1
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config
        DI_I_MAX: 0.4
        Gear_multiple: 20


  Auto_Set_Id_DeviceS0: &Auto_Set_Id_DeviceS0
    - Name: Auto_Set_Id_0
      DeviceType: Auto_Set_Id 
      Detect: false
      Id: 1
      CH: Head_Flag_Switch_CH2
      IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

      DeviceConfig:
        Run_Set: *Run_Auto_Set_Id
        Start_Id: 10
        Save_Id: *Auto_Set_Id_Save
        Time_Out_Ms: 1000
        DeviceList:
          --: *MotorS_0

Base_Node: 
  - Name: Main_Switch_Board
    Range_Name: X_Hand
    DeviceType: Switch_Board 
    Id: 101
    CH: Head_Flag_CH0
    IO_Mod: Main_CMD_IO_Mod_ETH_To_CAN
    PC_IP: *PC_IP
    IP: 192.168.3.101
    Port: 15100
    Up_Data_Speed: 10000
    Save_Config: *Save_Main_Config

    DeviceConfig:
      PrintMcuTaskStack: true
      Serial_S: *Serial_4_Config

    child:
      --: *Auto_Set_Id_DeviceS0
      --: *MotorS_0
      --: *Sensor_Custom


# std::map<std::string, u32> IO_Mod_Map = {
# {"Main_CMD_IO_Mod_ETH_To_CAN", Main_CMD_IO_Mod_ETH_To_CAN},
# {"Main_CMD_IO_Mod_ETH_OR_CAN", Main_CMD_IO_Mod_ETH_OR_CAN},
# {"Main_CMD_IO_Mod_CAN_ONLY", Main_CMD_IO_Mod_CAN_ONLY}};


# enum Motor_CONTROL_MOD
# {
# Motor_Current_Control = 10,
# Motor_MIT_Control = 11,
# Motor_Pos_Control = 12,
# Motor_Force_Control = 13,
# Motor_Speed_Control = 14,

# Motor_MOD_END = 100,
# };





