config:
  Serial_4_Config: &Serial_4_Config
    - Serial_CH: UART4
      Serial_menu: 4
      Serial_EN: true
      Serial_Baud: 921600
      Serial_ID: 200
      WordLength: UART_WORDLENGTH_8B
      Stm_Tx_Rx_GPIO:
        Tx_GPIO: GPIOD
        Rx_GPIO: GPIOD
        Tx_GPIO_PIN: GPIO_PIN_1
        Rx_GPIO_PIN: GPIO_PIN_0
      Other_Config:
        GPIO_AF: GPIO_AF8_UART4
        Serial_interrupt: UART4_IRQn
        TX_DMA: DMA_REQUEST_UART4_TX
        RX_DMA: DMA_REQUEST_UART4_RX
        TX_DMA_STREAM: DMA1_Stream3
        RX_DMA_STREAM: DMA1_Stream2

  Sensor_Custom: &Sensor_Custom
    - Name: Tactile_Sensor
      DeviceType: Tactile_Sensor_Custom
      Id: 200
      CH: Head_Flag_Switch_CH14