
config:
  Motor_default_config: &Motor_default_config
    #Zero
    Motor_Set_Zero_Offest: 0.0

    #Config
    Motor_Mod: Motor_MIT_Control
    Motor_Heart_Beat: 0
    Motor_Pole_Pairs: 1
    Motor_AB_Mirror: false
    Motor_current_sample_offset: 10

    Dead_Time: 0
    V_IC_MU_FORCE: 200
    IC_MU_SPEED: 1
    V_rated: 300

    DI_I_MAX: 0.4            
    I_Hardware_Max: 2
    Current_Amplifier_Gain: 10
    Motor_CMD_I_To_Force_K: 1.0

    Gear_Ratio: 27.16875
    Gear_multiple: 50
    
    # Pid_Config
    Electricity_D_P: 200000
    Electricity_D_I: 20000
    Electricity_D_OUT_MAX: 0.9
    Electricity_D_Integration_MAX: 0.9
    Electricity_Q_P: 200000
    Electricity_Q_I: 20000
    Electricity_Q_OUT_MAX: 0.9
    Electricity_Q_Integration_MAX: 0.9
