config:
  cat_motor_device_config: &cat_motor_device_config
    <<: *Usr_Motor_Init_Config
    <<: *Motor_default_config

  Motor_Config_Normal_0: &Motor_Config_Normal_0
    DeviceType: Motor_Device # Motor_Device IMU_Device Key_Device Switch_Board Custom_Device
    CH: Head_Flag_Switch_CH1
    IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

  Motor_Config_Normal_1: &Motor_Config_Normal_1
    DeviceType: Motor_Device # Motor_Device IMU_Device Key_Device Switch_Board Custom_Device
    CH: Head_Flag_Switch_CH2
    IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

  MotorS_0: &MotorS_0
    - Name: Motor_1
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config
        
    - Name: Motor_2
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_3
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_4
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_5
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_6
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_7
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_8
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_9
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_10
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_11
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_12
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_13
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_14
      Id: 1
      <<: *Motor_Config_Normal_0
      DeviceConfig: 
        <<: *cat_motor_device_config

  MotorS_1: &MotorS_1
    - Name: Motor_15
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config
        
    - Name: Motor_16
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_17
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_18
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_19
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_20
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_21
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_22
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_23
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_24
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_25
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_26
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_27
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

    - Name: Motor_28
      Id: 1
      <<: *Motor_Config_Normal_1
      DeviceConfig: 
        <<: *cat_motor_device_config

  Auto_Set_Id_DeviceS0: &Auto_Set_Id_DeviceS0
    - Name: Auto_Set_Id_0
      DeviceType: Auto_Set_Id 
      Detect: false
      Id: 1
      CH: Head_Flag_Switch_CH1
      IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

      DeviceConfig:
        Run_Set: *Run_Auto_Set_Id
        Start_Id: 11
        Save_Id: *Auto_Set_Id_Save
        Time_Out_Ms: 1000
        DeviceList:
          --: *MotorS_0

  Auto_Set_Id_DeviceS1: &Auto_Set_Id_DeviceS1
    - Name: Auto_Set_Id_1
      DeviceType: Auto_Set_Id 
      Detect: false
      Id: 2
      CH: Head_Flag_Switch_CH2
      IO_Mod: Main_CMD_IO_Mod_CAN_ONLY

      DeviceConfig:
        Run_Set: *Run_Auto_Set_Id
        Start_Id: 51
        Save_Id: *Auto_Set_Id_Save
        Time_Out_Ms: 1000
        DeviceList:
          --: *MotorS_1


Base_Node: 
  - Name: Main_Switch_Board
    Range_Name: Motor
    DeviceType: Switch_Board # Motor_Device IMU_Device Key_Device Switch_Board Custom_Device
    Id: 101
    # Rec_Id_Offest: [1536, 1024]
    CH: Head_Flag_CH0
    IO_Mod: Main_CMD_IO_Mod_ETH_To_CAN
    PC_IP: *PC_IP
    IP: 192.168.3.101
    Port: 15100
    Up_Data_Speed: 10000

    DeviceConfig:
      PrintMcuTaskStack: false

    child:
      --: *Auto_Set_Id_DeviceS0
      --: *MotorS_0

      --: *Auto_Set_Id_DeviceS1
      --: *MotorS_1


# std::map<std::string, u32> IO_Mod_Map = {
# {"Main_CMD_IO_Mod_ETH_To_CAN", Main_CMD_IO_Mod_ETH_To_CAN},
# {"Main_CMD_IO_Mod_ETH_OR_CAN", Main_CMD_IO_Mod_ETH_OR_CAN},
# {"Main_CMD_IO_Mod_CAN_ONLY", Main_CMD_IO_Mod_CAN_ONLY}};


# enum Motor_CONTROL_MOD
# {
# Motor_Current_Control = 10,
# Motor_MIT_Control = 11,
# Motor_Pos_Control = 12,
# Motor_Force_Control = 13,
# Motor_Speed_Control = 14,

# Motor_MOD_END = 100,
# };





